version: '3.1'

services:
  files_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - global

  api-clipis:
    build: ./api
    ports:
      - "8000:8000"
    links:
      - "files_db"
    volumes:
      - /home/farit/faiss_indices:/faiss_indices
    networks:
      - global

  front:
    build:
      context: ./clipis
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: "npm start"
    networks:
      - global

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - /home/farit/images:/static/media/images
    depends_on:
      - api-clipis
    networks:
      - global

volumes:
  faiss_indices:


networks:
  global:
    external: true
