version: '3.1'

services:
  files_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - global

  api:
    build: ./api
    ports:
      - "5000:80"
    links:
      - "files_db"
    networks:
      - global

  faiss:
    image: plippe/faiss-web-service:1.5.2
    ports:
      - "5050:5000"
    networks:
      - global

  front:
    build:
      context: ./clipis
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: "npm start"
    networks:
      - global

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - global

networks:
  global:
